# Generated by Django 5.2.7 on 2025-10-30 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_addr', models.CharField(max_length=45)),
                ('remote_user', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField()),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('request_path', models.TextField(blank=True)),
                ('protocol', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.PositiveBigIntegerField()),
                ('body_bytes_sent', models.PositiveBigIntegerField(blank=True, null=True)),
                ('referer', models.TextField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('raw_line', models.TextField(blank=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.source')),
            ],
            options={
                'indexes': [models.Index(fields=['remote_addr'], name='main_logent_remote__f46187_idx'), models.Index(fields=['status'], name='main_logent_status_ddaca7_idx'), models.Index(fields=['timestamp'], name='main_logent_timesta_dc43ff_idx')],
            },
        ),
    ]
