# Generated by Django 5.2.7 on 2025-10-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_uploadedlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedlog',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
